### ISSUE TITLE
No error on insufficient funds

### ISSUE THREAD

**Issue by monsterbitar** [cashninjas/ninjas.cash#2]
I tried to mint a ninja and it just said building transaction 1/1.

When I looked into the console it says:

> Error: Insufficient funds: available (110002000) < needed (110002511).

Given that the cost to mint is supposed to be 0.05 BCH, I don't intuitively understand what these numbers correspond to, but there should be a user-interface error shown that helps the user resolve the situation.

**Comment by zquestz** [comment]
Noted, we are adding better error handling for this case.

**Comment by zquestz** [comment]
I have pushed changes that dramatically improve the error handling. Thanks for pointing this out. =)
