### ISSUE TITLE
Insufficient funds, take 2

### ISSUE THREAD

**Issue by monsterbitar** [cashninjas/ninjas.cash#3]
After previous failure to mint due to unsuccessful funds, I sent another €0.02 and tried again.

The result remained the same, so I assume the coin selection wants to take all the coins from a single address, but the wallet receive screen has no way to send to that specific address.

I am using the Zapit! wallet for this attempt in minting.

**Comment by monsterbitar** [comment]
I manually sent more funds to the specific address that was being used according to the wallet:

https://blockchair.com/bitcoin-cash/address/qzryqdjh7rrmz7y7kg689ug8y5rpjs8hks5mmexa43

The result is the same, as if it didn't see any further UTXOs.
![image](https://github.com/cashninjas/ninjas.cash/assets/8721695/221d105f-adb4-43f4-80db-b56ef9de39fe)

**Comment by zquestz** [comment]
@monsterbitar sorry for the delayed reply.

There is no auto utxo consolidation and the contract expects exactly 1 input UTXO.

We are improving the error messaging for this case. For now you can just send max balance back to yourself to consolidate, and the error will disappear.

**Comment by monsterbitar** [comment]
Right, I eventually got around to doing that manually and now zapit's wallet-connect feature is working so I have myself a ninja.

you can close this when/if you no longer need the issue.
